/**
 * This file was generated by Api2Pojo
 * See <a href="https://github.com/mmzitarosa/Api2Pojo">https://github.com/mmzitarosa/Api2Pojo</a>
 * Any modifications to this file will be lost upon recompilation of the source schema.
 * Generated on: Sun Feb 23 15:53:31 CET 2020
 */
package com.punkapi.api2pojo.beers;

import java.util.ArrayList;
import java.util.List;

public class BeersItem {

    private String first_brewed;
    private Number attenuation_level;
    private Method method;
    private Number target_og;
    private String image_url;
    private Boil_volume boil_volume;
    private Number ebc;
    private String description;
    private Number target_fg;
    private Number srm;
    private Volume volume;
    private String contributed_by;
    private Number abv;
    private List<String> food_pairing;
    private String name;
    private Number ph;
    private String tagline;
    private Ingredients ingredients;
    private Number id;
    private Number ibu;
    private String brewers_tips;

    public BeersItem() {
        this.food_pairing = new ArrayList<String>();
    }

    public BeersItem(String first_brewed, Number attenuation_level, Method method, Number target_og, String image_url, Boil_volume boil_volume, Number ebc, String description, Number target_fg, Number srm, Volume volume, String contributed_by, Number abv, List<String> food_pairing, String name, Number ph, String tagline, Ingredients ingredients, Number id, Number ibu, String brewers_tips) {
        this.first_brewed = first_brewed;
        this.attenuation_level = attenuation_level;
        this.method = method;
        this.target_og = target_og;
        this.image_url = image_url;
        this.boil_volume = boil_volume;
        this.ebc = ebc;
        this.description = description;
        this.target_fg = target_fg;
        this.srm = srm;
        this.volume = volume;
        this.contributed_by = contributed_by;
        this.abv = abv;
        this.food_pairing = food_pairing;
        this.name = name;
        this.ph = ph;
        this.tagline = tagline;
        this.ingredients = ingredients;
        this.id = id;
        this.ibu = ibu;
        this.brewers_tips = brewers_tips;
    }

    public String getFirst_brewed() {
        return this.first_brewed;
    }

    public void setFirst_brewed(String first_brewed) {
        this.first_brewed = first_brewed;
    }

    public Number getAttenuation_level() {
        return this.attenuation_level;
    }

    public void setAttenuation_level(Number attenuation_level) {
        this.attenuation_level = attenuation_level;
    }

    public Method getMethod() {
        return this.method;
    }

    public void setMethod(Method method) {
        this.method = method;
    }

    public Number getTarget_og() {
        return this.target_og;
    }

    public void setTarget_og(Number target_og) {
        this.target_og = target_og;
    }

    public String getImage_url() {
        return this.image_url;
    }

    public void setImage_url(String image_url) {
        this.image_url = image_url;
    }

    public Boil_volume getBoil_volume() {
        return this.boil_volume;
    }

    public void setBoil_volume(Boil_volume boil_volume) {
        this.boil_volume = boil_volume;
    }

    public Number getEbc() {
        return this.ebc;
    }

    public void setEbc(Number ebc) {
        this.ebc = ebc;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Number getTarget_fg() {
        return this.target_fg;
    }

    public void setTarget_fg(Number target_fg) {
        this.target_fg = target_fg;
    }

    public Number getSrm() {
        return this.srm;
    }

    public void setSrm(Number srm) {
        this.srm = srm;
    }

    public Volume getVolume() {
        return this.volume;
    }

    public void setVolume(Volume volume) {
        this.volume = volume;
    }

    public String getContributed_by() {
        return this.contributed_by;
    }

    public void setContributed_by(String contributed_by) {
        this.contributed_by = contributed_by;
    }

    public Number getAbv() {
        return this.abv;
    }

    public void setAbv(Number abv) {
        this.abv = abv;
    }

    public List<String> getFood_pairing() {
        return this.food_pairing;
    }

    public void setFood_pairing(List<String> food_pairing) {
        this.food_pairing = food_pairing;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Number getPh() {
        return this.ph;
    }

    public void setPh(Number ph) {
        this.ph = ph;
    }

    public String getTagline() {
        return this.tagline;
    }

    public void setTagline(String tagline) {
        this.tagline = tagline;
    }

    public Ingredients getIngredients() {
        return this.ingredients;
    }

    public void setIngredients(Ingredients ingredients) {
        this.ingredients = ingredients;
    }

    public Number getId() {
        return this.id;
    }

    public void setId(Number id) {
        this.id = id;
    }

    public Number getIbu() {
        return this.ibu;
    }

    public void setIbu(Number ibu) {
        this.ibu = ibu;
    }

    public String getBrewers_tips() {
        return this.brewers_tips;
    }

    public void setBrewers_tips(String brewers_tips) {
        this.brewers_tips = brewers_tips;
    }

}