/**
 * This file was generated by Api2Pojo
 * <p>
 * See <a href="https://github.com/mmzitarosa/Api2Pojo">https://github.com/mmzitarosa/Api2Pojo</a>
 * Any modifications to this file will be lost upon recompilation of the source schema.
 * Generated on: Sun Feb 23 15:53:31 CET 2020
 */

package com.punkapi.api2pojo.beers;

import java.util.ArrayList;
import java.util.List;

public class Beers {

    private List<BeersItem> beersItem;

    public Beers() {
        this.beersItem = new ArrayList<BeersItem>();
    }

    public Beers(List<BeersItem> beersItem) {
        this.beersItem = beersItem;
    }

    public List<BeersItem> getBeersItem() {
        return this.beersItem;
    }

    public void setBeersItem(List<BeersItem> beersItem) {
        this.beersItem = beersItem;
    }

}