/**
 * This file was generated by Api2Pojo
 * See <a href="https://github.com/mmzitarosa/Api2Pojo">https://github.com/mmzitarosa/Api2Pojo</a>
 * Any modifications to this file will be lost upon recompilation of the source schema.
 * Generated on: Sun Feb 23 15:53:31 CET 2020
 */

package com.punkapi.api2pojo.beers;

public class Hops {

    private String add;
    private Amount amount;
    private String name;
    private String attribute;

    public Hops() {
    }

    public Hops(String add, Amount amount, String name, String attribute) {
        this.add = add;
        this.amount = amount;
        this.name = name;
        this.attribute = attribute;
    }

    public String getAdd() {
        return this.add;
    }

    public void setAdd(String add) {
        this.add = add;
    }

    public Amount getAmount() {
        return this.amount;
    }

    public void setAmount(Amount amount) {
        this.amount = amount;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAttribute() {
        return this.attribute;
    }

    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }

}