/**
 * This file was generated by Api2Pojo
 * See <a href="https://github.com/mmzitarosa/Api2Pojo">https://github.com/mmzitarosa/Api2Pojo</a>
 * Any modifications to this file will be lost upon recompilation of the source schema.
 * Generated on: Sun Feb 23 15:53:31 CET 2020
 */

package com.punkapi.api2pojo.beers;

import java.util.ArrayList;
import java.util.List;

public class Ingredients {

    private List<Hops> hops;
    private String yeast;
    private List<Malt> malt;

    public Ingredients() {
        this.hops = new ArrayList<Hops>();
        this.malt = new ArrayList<Malt>();
    }

    public Ingredients(List<Hops> hops, String yeast, List<Malt> malt) {
        this.hops = hops;
        this.yeast = yeast;
        this.malt = malt;
    }

    public List<Hops> getHops() {
        return this.hops;
    }

    public void setHops(List<Hops> hops) {
        this.hops = hops;
    }

    public String getYeast() {
        return this.yeast;
    }

    public void setYeast(String yeast) {
        this.yeast = yeast;
    }

    public List<Malt> getMalt() {
        return this.malt;
    }

    public void setMalt(List<Malt> malt) {
        this.malt = malt;
    }

}