/**
 * This file was generated by Api2Pojo
 * See <a href="https://github.com/mmzitarosa/Api2Pojo">https://github.com/mmzitarosa/Api2Pojo</a>
 * Any modifications to this file will be lost upon recompilation of the source schema.
 * Generated on: Sun Feb 23 15:53:31 CET 2020
 */

package com.punkapi.api2pojo.beers;

public class Mash_temp {

    private Number duration;
    private Temp temp;

    public Mash_temp() {
    }

    public Mash_temp(Number duration, Temp temp) {
        this.duration = duration;
        this.temp = temp;
    }

    public Number getDuration() {
        return this.duration;
    }

    public void setDuration(Number duration) {
        this.duration = duration;
    }

    public Temp getTemp() {
        return this.temp;
    }

    public void setTemp(Temp temp) {
        this.temp = temp;
    }

}