/**
 * This file was generated by Api2Pojo
 * See <a href="https://github.com/mmzitarosa/Api2Pojo">https://github.com/mmzitarosa/Api2Pojo</a>
 * Any modifications to this file will be lost upon recompilation of the source schema.
 * Generated on: Sun Feb 23 15:53:31 CET 2020
 */

package com.punkapi.api2pojo.beers;

import java.util.ArrayList;
import java.util.List;

public class Method {

    private List<Mash_temp> mash_temp;
    private Fermentation fermentation;
    private Object twist;

    public Method() {
        this.mash_temp = new ArrayList<Mash_temp>();
    }

    public Method(List<Mash_temp> mash_temp, Fermentation fermentation, Object twist) {
        this.mash_temp = mash_temp;
        this.fermentation = fermentation;
        this.twist = twist;
    }

    public List<Mash_temp> getMash_temp() {
        return this.mash_temp;
    }

    public void setMash_temp(List<Mash_temp> mash_temp) {
        this.mash_temp = mash_temp;
    }

    public Fermentation getFermentation() {
        return this.fermentation;
    }

    public void setFermentation(Fermentation fermentation) {
        this.fermentation = fermentation;
    }

    public Object getTwist() {
        return this.twist;
    }

    public void setTwist(Object twist) {
        this.twist = twist;
    }

}